{
    "openapi": "3.0.1",
    "info": {
      "title": "RSSFeedify API",
      "version": "1.0"
    },
    "paths": {
      "/api/RSSFeedItems": {
        "get": {
          "tags": [
            "RSSFeedItems"
          ],
          "parameters": [
            {
              "name": "byRSSFeedGuid",
              "in": "query",
              "schema": {
                "type": "string"
              }
            },
            {
              "name": "page",
              "in": "query",
              "schema": {
                "type": "integer",
                "format": "int32"
              }
            },
            {
              "name": "pageSize",
              "in": "query",
              "schema": {
                "type": "integer",
                "format": "int32"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/RSSFeedItem"
                    }
                  }
                },
                "application/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/RSSFeedItem"
                    }
                  }
                },
                "text/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/RSSFeedItem"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/api/RSSFeedItems/count": {
        "get": {
          "tags": [
            "RSSFeedItems"
          ],
          "parameters": [
            {
              "name": "byRSSFeedGuid",
              "in": "query",
              "schema": {
                "type": "string"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "type": "integer",
                    "format": "int32"
                  }
                },
                "application/json": {
                  "schema": {
                    "type": "integer",
                    "format": "int32"
                  }
                },
                "text/json": {
                  "schema": {
                    "type": "integer",
                    "format": "int32"
                  }
                }
              }
            }
          }
        }
      },
      "/api/RSSFeedItems/{guid}": {
        "get": {
          "tags": [
            "RSSFeedItems"
          ],
          "parameters": [
            {
              "name": "guid",
              "in": "path",
              "required": true,
              "schema": {
                "type": "string"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeedItem"
                  }
                },
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeedItem"
                  }
                },
                "text/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeedItem"
                  }
                }
              }
            }
          }
        },
        "delete": {
          "tags": [
            "RSSFeedItems"
          ],
          "parameters": [
            {
              "name": "guid",
              "in": "path",
              "required": true,
              "schema": {
                "type": "string"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeedItem"
                  }
                },
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeedItem"
                  }
                },
                "text/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeedItem"
                  }
                }
              }
            }
          }
        }
      },
      "/api/RSSFeeds": {
        "get": {
          "tags": [
            "RSSFeeds"
          ],
          "parameters": [
            {
              "name": "page",
              "in": "query",
              "schema": {
                "type": "integer",
                "format": "int32"
              }
            },
            {
              "name": "pageSize",
              "in": "query",
              "schema": {
                "type": "integer",
                "format": "int32"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/RSSFeed"
                    }
                  }
                },
                "application/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/RSSFeed"
                    }
                  }
                },
                "text/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/RSSFeed"
                    }
                  }
                }
              }
            }
          }
        },
        "post": {
          "tags": [
            "RSSFeeds"
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RSSFeedDTO"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/RSSFeedDTO"
                }
              },
              "application/*+json": {
                "schema": {
                  "$ref": "#/components/schemas/RSSFeedDTO"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                },
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                },
                "text/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                }
              }
            }
          }
        }
      },
      "/api/RSSFeeds/{guid}": {
        "get": {
          "tags": [
            "RSSFeeds"
          ],
          "parameters": [
            {
              "name": "guid",
              "in": "path",
              "required": true,
              "schema": {
                "type": "string"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                },
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                },
                "text/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                }
              }
            }
          }
        },
        "put": {
          "tags": [
            "RSSFeeds"
          ],
          "parameters": [
            {
              "name": "guid",
              "in": "path",
              "required": true,
              "schema": {
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RSSFeedDTO"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/RSSFeedDTO"
                }
              },
              "application/*+json": {
                "schema": {
                  "$ref": "#/components/schemas/RSSFeedDTO"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                },
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                },
                "text/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                }
              }
            }
          }
        },
        "delete": {
          "tags": [
            "RSSFeeds"
          ],
          "parameters": [
            {
              "name": "guid",
              "in": "path",
              "required": true,
              "schema": {
                "type": "string"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                },
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                },
                "text/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RSSFeed"
                  }
                }
              }
            }
          }
        }
      },
      "/api/RSSFeeds/count": {
        "get": {
          "tags": [
            "RSSFeeds"
          ],
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "text/plain": {
                  "schema": {
                    "type": "integer",
                    "format": "int32"
                  }
                },
                "application/json": {
                  "schema": {
                    "type": "integer",
                    "format": "int32"
                  }
                },
                "text/json": {
                  "schema": {
                    "type": "integer",
                    "format": "int32"
                  }
                }
              }
            }
          }
        }
      }
    },
    "components": {
      "schemas": {
        "RSSFeed": {
          "type": "object",
          "properties": {
            "guid": {
              "type": "string",
              "format": "uuid"
            },
            "createdAt": {
              "type": "string",
              "format": "date-time"
            },
            "updatedAt": {
              "type": "string",
              "format": "date-time"
            },
            "name": {
              "type": "string",
              "nullable": true
            },
            "description": {
              "type": "string",
              "nullable": true
            },
            "sourceUrl": {
              "type": "string",
              "format": "uri",
              "nullable": true
            },
            "pollingInterval": {
              "type": "number",
              "format": "double"
            },
            "lastPoll": {
              "type": "string",
              "format": "date-time"
            },
            "lastSuccessfullPoll": {
              "type": "string",
              "format": "date-time"
            }
          },
          "additionalProperties": false
        },
        "RSSFeedDTO": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "nullable": true
            },
            "description": {
              "type": "string",
              "nullable": true
            },
            "sourceUrl": {
              "type": "string",
              "format": "uri",
              "nullable": true
            },
            "pollingInterval": {
              "type": "number",
              "format": "double"
            }
          },
          "additionalProperties": false
        },
        "RSSFeedItem": {
          "type": "object",
          "properties": {
            "guid": {
              "type": "string",
              "format": "uuid"
            },
            "createdAt": {
              "type": "string",
              "format": "date-time"
            },
            "updatedAt": {
              "type": "string",
              "format": "date-time"
            },
            "hash": {
              "type": "string",
              "nullable": true
            },
            "title": {
              "type": "string",
              "nullable": true
            },
            "summary": {
              "type": "string",
              "nullable": true
            },
            "publishDate": {
              "type": "string",
              "format": "date-time"
            },
            "links": {
              "type": "array",
              "items": {
                "type": "string",
                "format": "uri"
              },
              "nullable": true
            },
            "categories": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "nullable": true
            },
            "authors": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "nullable": true
            },
            "contributors": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "nullable": true
            },
            "content": {
              "type": "string",
              "nullable": true
            },
            "id": {
              "type": "string",
              "nullable": true
            },
            "rssFeedId": {
              "type": "string",
              "format": "uuid"
            }
          },
          "additionalProperties": false
        }
      }
    }
  }



